import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from "react-router-dom";
const metrics = [
    { label: "Portales", value: "3" },
    { label: "Cobertura", value: "Admin, cliente y socios" },
    { label: "Motor", value: "e-CF + DGII + Odoo" },
];
export function HomePage() {
    return (_jsxs("div", { className: "mx-auto max-w-7xl px-6 py-14", children: [_jsxs("section", { className: "grid gap-10 lg:grid-cols-[1.15fr,0.85fr] lg:items-center", children: [_jsxs("div", { className: "space-y-6", children: [_jsx("span", { className: "inline-flex rounded-full border border-accent/25 bg-accent/10 px-4 py-1 text-xs font-semibold uppercase tracking-[0.24em] text-accent", children: "Tax-tech y operaciones" }), _jsxs("div", { className: "space-y-4", children: [_jsx("h1", { className: "max-w-3xl text-5xl font-semibold leading-tight text-ink", children: "Gestion fiscal, contable y operativa desde una sola plataforma." }), _jsx("p", { className: "max-w-2xl text-lg text-slate-600", children: "GetUpSoft centraliza facturacion electronica, trazabilidad documental, control multiempresa y operacion contable con un enfoque listo para Republica Dominicana." })] }), _jsxs("div", { className: "flex flex-wrap gap-4", children: [_jsx("a", { className: "rounded-full bg-ink px-6 py-3 text-sm font-semibold text-white hover:bg-accent", href: "https://cliente.getupsoft.com.do/login", children: "Solicitar demo" }), _jsx(Link, { className: "rounded-full border border-slate-300 px-6 py-3 text-sm font-semibold text-slate-800 hover:border-accent hover:text-accent", to: "/productos/accounting-management", children: "Ver Accounting Management" })] })] }), _jsx("div", { className: "grid gap-4 rounded-[2rem] border border-slate-200 bg-white/90 p-8 shadow-[0_30px_90px_rgba(15,23,42,0.08)]", children: metrics.map((metric) => (_jsxs("div", { className: "rounded-2xl border border-slate-200 bg-slate-50 px-5 py-4", children: [_jsx("p", { className: "text-xs uppercase tracking-[0.24em] text-slate-500", children: metric.label }), _jsx("p", { className: "mt-2 text-xl font-semibold text-ink", children: metric.value })] }, metric.label))) })] }), _jsxs("section", { className: "mt-20 grid gap-6 md:grid-cols-3", children: [_jsxs("article", { className: "rounded-[1.75rem] border border-slate-200 bg-white/85 p-6", children: [_jsx("p", { className: "text-sm font-semibold text-ink", children: "Cumplimiento" }), _jsx("p", { className: "mt-3 text-sm text-slate-600", children: "Flujos preparados para e-CF, evidencia operativa y reportes orientados a DGII." })] }), _jsxs("article", { className: "rounded-[1.75rem] border border-slate-200 bg-white/85 p-6", children: [_jsx("p", { className: "text-sm font-semibold text-ink", children: "Control" }), _jsx("p", { className: "mt-3 text-sm text-slate-600", children: "Portales diferenciados para plataforma, clientes y socios, con RBAC y segregacion por tenant." })] }), _jsxs("article", { className: "rounded-[1.75rem] border border-slate-200 bg-white/85 p-6", children: [_jsx("p", { className: "text-sm font-semibold text-ink", children: "Integracion" }), _jsx("p", { className: "mt-3 text-sm text-slate-600", children: "Ruta de integracion con Odoo 19, reportes contables y operacion multiempresa." })] })] })] }));
}
