import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NavLink, Outlet } from "react-router-dom";
const NAV = [
    { to: "/", label: "Inicio" },
    { to: "/productos", label: "Productos" },
    { to: "/plataforma", label: "Plataforma" },
    { to: "/contacto", label: "Contacto" },
];
export function SiteLayout() {
    return (_jsxs("div", { className: "min-h-screen", children: [_jsx("header", { className: "sticky top-0 z-20 border-b border-slate-200/70 bg-sand/90 backdrop-blur", children: _jsxs("div", { className: "mx-auto flex max-w-7xl items-center justify-between px-6 py-4", children: [_jsxs("div", { children: [_jsx("p", { className: "text-xs uppercase tracking-[0.28em] text-slate-500", children: "GetUpSoft" }), _jsx("p", { className: "text-lg font-semibold text-ink", children: "Plataforma fiscal y operativa" })] }), _jsx("nav", { className: "hidden gap-6 text-sm font-medium text-slate-700 md:flex", children: NAV.map((item) => (_jsx(NavLink, { to: item.to, className: ({ isActive }) => (isActive ? "text-accent" : "hover:text-accent"), children: item.label }, item.to))) }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("a", { className: "rounded-full border border-slate-300 px-4 py-2 text-sm hover:border-accent hover:text-accent", href: "https://admin.getupsoft.com.do/login", children: "Admin" }), _jsx("a", { className: "rounded-full bg-ink px-4 py-2 text-sm font-semibold text-white hover:bg-accent", href: "https://cliente.getupsoft.com.do/login", children: "Ingresar" })] })] }) }), _jsx("main", { children: _jsx(Outlet, {}) }), _jsx("footer", { className: "border-t border-slate-200/80 bg-white/70", children: _jsxs("div", { className: "mx-auto grid max-w-7xl gap-6 px-6 py-10 md:grid-cols-3", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-ink", children: "GetUpSoft" }), _jsx("p", { className: "mt-2 text-sm text-slate-600", children: "Software tax-tech y operaciones contables para empresas, partners y equipos administrativos." })] }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-ink", children: "Accesos" }), _jsxs("ul", { className: "mt-2 space-y-2 text-sm text-slate-600", children: [_jsx("li", { children: _jsx("a", { href: "https://admin.getupsoft.com.do/login", children: "Admin" }) }), _jsx("li", { children: _jsx("a", { href: "https://cliente.getupsoft.com.do/login", children: "Clientes" }) }), _jsx("li", { children: _jsx("a", { href: "https://socios.getupsoft.com.do/login", children: "Socios" }) })] })] }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-ink", children: "Producto destacado" }), _jsx("p", { className: "mt-2 text-sm text-slate-600", children: "Accounting Management: gestion contable, cumplimiento fiscal, reportes DGII y operacion multiempresa." })] })] }) })] }));
}
